Modified for new version.

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -3,23 +3,46 @@
 
 # fail fast
 set -e
+# STACK=cedar-14
+if [ "${STACK}" != "cedar-14" ]; then
+	echo "Stack ${STACK} not supported." && exit 1
+else
+	echo "Stack is done! $STACK"
+fi
 
-if [ $STACK != "cedar-14" ]; then
-	echo "Stack ${STACK} not supported" && exit 1
+if [ "$1" == "" ]; then
+	echo "Build dir is not found." && exit 1
+fi
+
+if [ "$2" == "" ]; then
+	echo "Cache dir is not found." && exit 1
+fi
+
+if [ "$3" == "" ]; then
+	echo "Environment dir is not found." && exit 1
 fi
 
 BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
+APP_DIR="/app"
+
+echo "BUILD_DIR: ${BUILD_DIR}"
+echo "CACHE_DIR: ${CACHE_DIR}"
+echo "ENV_DIR: ${ENV_DIR}"
+echo "APP_DIR: ${APP_DIR}"
+
 # This is where the buildpack is stored
 BUILDPACK_DIR=`cd $(dirname $0); cd ..; pwd`
+
+echo "Buildpack dir is : ${BUILDPACK_DIR}"
 
 source $BUILDPACK_DIR/bin/util
 
 export_env_dir ${ENV_DIR}
 
 : ${CORE_VERSION:="latest"}
-: ${CORE_SCRIPT_LOCATION:="https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh"}
+: ${CORE_SCRIPT_LOCATION:="https://dot.net/v1/dotnet-install.sh"}
 : ${NODE_VERSION:="4.4.4"}
 : ${CORE_VERSION:="latest"}
 : ${CORE_CHANNEL:="preview"}
@@ -33,13 +56,15 @@ else
 fi
 
 SRC_DIR=`mktemp -d`
+echo "Temp folder created on ${SRC_DIR}"
 # Move the app source code into temporary src dir using subshell to not leak shopt
 (
 	shopt -s dotglob
-	mv ${BUILD_DIR}/* ${SRC_DIR}
+	cp -ai ${BUILD_DIR} ${SRC_DIR}
 )
 
 mkdir -p ${CACHE_DIR}
+echo "Cache folder created on ${CACHE_DIR}"
 
 # TODO: This test doesn't seen to actually work
 # TODO: Maybe just run `npm install -g` and if anything is missing, install it after
@@ -56,73 +81,80 @@ then
 	fi
 fi
 
-# Install .NET Core
-echo "Get .NET Core Version and Channel from the PROJECT"
-DEPLOYMENT_FILE_LOCATION=${SRC_DIR}/.deployment
-if [ -n "$(find ${SRC_DIR}/global.json)" ]; then
-	echo "Get version from global.json"
-	CORE_VERSION=$(ruby -rjson -e "j = JSON.parse(File.open('${SRC_DIR}/global.json','r:bom|utf-8').read); unless j['sdk'].nil? ; puts j['sdk']['version'];end")
-	if [ -z "${CORE_VERSION}" ]; then
-		CORE_VERSION="latest"
-	elif [[ "${CORE_VERSION}" != "latest" ]]; then
-		if [[ "${CORE_VERSION}" == "1.0.0-preview2.1-003155" ]]; then
-			CORE_DOWNLOAD_LOCATION="https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2.1-003155/dotnet-dev-ubuntu-x64.1.0.0-preview2.1-003155.tar.gz"
-		elif [[ "${CORE_VERSION}" > "1.0.0-preview2-003121" ]]; then
-			#TODO
-			CORE_DOWNLOAD_LOCATION="https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-ubuntu-x64.latest.tar.gz"
-		elif [[ ! "${CORE_VERSION}" > "1.0.0-preview1-002702" ]]; then
-			CORE_CHANNEL="beta"
+## Check if already installed.
+if [ ! -d "$CACHE_DIR/dotnet" ]; then
+	# Install .NET Core
+	echo "Getting .NET Core Version and Channel from the PROJECT"
+	DEPLOYMENT_FILE_LOCATION=${SRC_DIR}/.deployment
+	if [ -n "$(find ${SRC_DIR}/global.json)" ]; then
+		echo "Get version from global.json"
+		CORE_VERSION=$(ruby -rjson -e "j = JSON.parse(File.open('${SRC_DIR}/global.json','r:bom|utf-8').read); unless j['sdk'].nil? ; puts j['sdk']['version'];end")
+		if [ -z "${CORE_VERSION}" ]; then
+			CORE_VERSION="latest"
+		elif [[ "${CORE_VERSION}" != "latest" ]]; then
+			if [[ "${CORE_VERSION}" == "1.0.0-preview2.1-003155" ]]; then
+				CORE_DOWNLOAD_LOCATION="https://dotnetcli.blob.core.windows.net/dotnet/preview/Binaries/1.0.0-preview2.1-003155/dotnet-dev-ubuntu-x64.1.0.0-preview2.1-003155.tar.gz"
+			elif [[ "${CORE_VERSION}" > "1.0.0-preview2-003121" ]]; then
+				#TODO
+				CORE_DOWNLOAD_LOCATION="https://dotnetcli.blob.core.windows.net/dotnet/Sdk/rel-1.0.0/dotnet-dev-ubuntu-x64.latest.tar.gz"
+			elif [[ ! "${CORE_VERSION}" > "1.0.0-preview1-002702" ]]; then
+				CORE_CHANNEL="beta"
+			fi
 		fi
 	fi
-fi
 
-if [[ "${CORE_VERSION}" == "latest" && -e "${DEPLOYMENT_FILE_LOCATION}" ]]; then
-	CORE_CHANNEL_TMP=$(awk -F "=" '/channel/ {print $2}' ${DEPLOYMENT_FILE_LOCATION} | tr -d ' ')
-	if [ ! -z "${CORE_CHANNEL_TMP}" ]; then
-		CORE_CHANNEL="${CORE_CHANNEL_TMP}"
+	if [[ "${CORE_VERSION}" == "latest" && -e "${DEPLOYMENT_FILE_LOCATION}" ]]; then
+		CORE_CHANNEL_TMP=$(awk -F "=" '/channel/ {print $2}' ${DEPLOYMENT_FILE_LOCATION} | tr -d ' ')
+		if [ ! -z "${CORE_CHANNEL_TMP}" ]; then
+			CORE_CHANNEL="${CORE_CHANNEL_TMP}"
+		fi
 	fi
-fi
 
-# Temporary fix noliar/dotnet-buildpack#8
-if [[ "${CORE_VERSION}" == "latest" && "${CORE_CHANNEL}" == "preview" ]]; then
-	CORE_VERSION="1.0.0-preview2-003121"
-fi
+	# Temporary fix noliar/dotnet-buildpack#8
+	if [[ "${CORE_VERSION}" == "latest" && "${CORE_CHANNEL}" == "preview" ]]; then
+		CORE_VERSION="latest"
+	fi
 
-CORE_VERSION_FIRST="$CORE_VERSION"
-CORE_DOWNLOAD_LOCATION="https://go.microsoft.com/fwlink/?LinkID=834989"
-#if [[ "${CORE_VERSION}" == "latest" ]]; then
-#	CORE_VERSION_FIRST="Latest"
-#	${CORE_DOWNLOAD_LOCATION:="https://go.microsoft.com/fwlink/?LinkID=834989"}
-#else
-#	: ${CORE_DOWNLOAD_LOCATION:="https://dotnetcli.blob.core.windows.net/dotnet/${CORE_CHANNEL}/Binaries/${CORE_VERSION_FIRST}/dotnet-dev-ubuntu-x64.${CORE_VERSION}.tar.gz"}
-#fi
+	CORE_VERSION_FIRST="$CORE_VERSION"
+	# This is the latest one : .NET Core 1.1.1
+	CORE_DOWNLOAD_LOCATION="https://go.microsoft.com/fwlink/?linkid=847090"
+	if [[ "${CORE_VERSION}" != "latest" ]]; then
+		CORE_DOWNLOAD_LOCATION="https://dotnetcli.blob.core.windows.net/dotnet/${CORE_CHANNEL}/Binaries/${CORE_VERSION_FIRST}/dotnet-dev-ubuntu-x64.${CORE_VERSION}.tar.gz"
+	fi
 
-echo "Installing the dependencies"
-apt_install libunwind8 gettext
+	echo "Installing the dependencies"
 
-mkdir -p ${BUILD_DIR}/dotnet
+	#### apt_install libunwind8 gettext
 
-echo "Installing .NET CORE ${CORE_VERSION} from ${CORE_DOWNLOAD_LOCATION}"
-# dotnet-install.sh using `ldconfig` which search pkg in `/lib` or `/usr/lib`. So I change it to binaries.
-#curl -sSL ${CORE_SCRIPT_LOCATION} | bash /dev/stdin --version ${CORE_VERSION} --install-dir ${BUILD_DIR}/dotnet
-curl ${CORE_DOWNLOAD_LOCATION} -Ls | tar xz -C ${BUILD_DIR}/dotnet
-ln -s ${BUILD_DIR}/dotnet /app
+	mkdir -p ${BUILD_DIR}/dotnet
 
-export PATH="/app/dotnet:${PATH}"
-export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}"
+	DL_FILE="${CACHE_DIR}/dotnet.tar.gz"
 
-if [ -n "$PROJECT" ]; then
-	PROJECT_JSON_FILE=${SRC_DIR}/${PROJECT}
-	echo "Project file configured in PROJECT environment variable"
-elif [ -e ${DEPLOYMENT_FILE_LOCATION} ]; then
-	PROJECT_JSON_FILE=${SRC_DIR}/$(awk -F "=" '/project/ {print $2}' ${DEPLOYMENT_FILE_LOCATION} | tr -d ' ')
-	echo "Project file configured in .deployment file"
+	echo "Downloading .NET CORE ${CORE_VERSION} from ${CORE_DOWNLOAD_LOCATION} to ${DL_FILE}"
+	# dotnet-install.sh using `ldconfig` which search pkg in `/lib` or `/usr/lib`. So I change it to binaries.
+	#curl -sSL ${CORE_SCRIPT_LOCATION} | bash /dev/stdin --version ${CORE_VERSION} --install-dir ${BUILD_DIR}/dotnet
+	curl -o "${DL_FILE}" -# "${CORE_DOWNLOAD_LOCATION}" -L
+	echo "Download complete."
+	echo "Path is : ${DL_FILE}"
+	echo "Extracting downloaded files"
+	tar xf "${DL_FILE}" -C ${CACHE_DIR}/dotnet
+	echo "Done!"
+
+	ln -s ${CACHE_DIR}/dotnet "${APP_DIR}"
 else
-	PROJECT_JSON_FILES=$(find ${SRC_DIR}/. -maxdepth 5 -iname "project.json")
-	printf 'Found %s project.json files\n' $(echo "$PROJECT_JSON_FILES" | wc -l | tr -d ' ')
-	PROJECT_JSON_FILE=$(echo "$PROJECT_JSON_FILES" | head -1)
-	PROJECT_JSON_FILE=$(readlink -m $PROJECT_JSON_FILE)
+	echo "Dotnet already installed."
 fi
+## Check if already installed
+
+export PATH="${APP_DIR}/dotnet:${PATH}"
+export LD_LIBRARY_PATH="${LD_LIBRARY_PATH}"
+echo "Paths are exported."
+echo "Deployment file location is ${DEPLOYMENT_FILE_LOCATION}"
+
+PROJECT_JSON_FILES=$(find ${SRC_DIR}/. -maxdepth 5 -iname "*.csproj")
+printf 'Found %s csproj files\n' $(echo "$PROJECT_JSON_FILES" | wc -l | tr -d ' ')
+PROJECT_JSON_FILE=$(echo "$PROJECT_JSON_FILES" | head -1)
+
 echo "Building ${PROJECT_JSON_FILE}"
 
 PROJECT_DIR="$PROJECT_JSON_FILE"
@@ -130,14 +162,23 @@ if [[ -f $PROJECT_JSON_FILE ]]; then
 	PROJECT_DIR=$(dirname $PROJECT_JSON_FILE)
 fi
 
-echo "Reading App Name from project.json"
+echo "Project dir is ${PROJECT_DIR}"
+echo "Reading App Name from csproj"
+
 PROJECT_DIR_NAME=$(basename $PROJECT_DIR)
-PROJECT_NAME=$(ruby -rjson -e "j = JSON.parse(File.open('${PROJECT_DIR}/project.json','r:bom|utf-8').read); unless j['buildOptions'].nil? ; puts j['buildOptions']['outputName'];end")
-echo "${PROJECT_NAME:=$PROJECT_DIR_NAME}"
+PROJECT_NAME=$(awk -F '[<>]' '/AssemblyName/{print $3}' $PROJECT_JSON_FILE)
 
+if [ -z "$PROJECT_NAME" ]; then
+	echo "Assembly name not founded in csproj. Getting csproj file name."
+	FULLFILENAME=$(basename $PROJECT_JSON_FILE)
+	EXTRACTED_FILE_NAME="${FULLFILENAME%.*}"
+	PROJECT_NAME=$EXTRACTED_FILE_NAME
+fi
+
+echo "Founded name is $PROJECT_NAME"
 echo "Restoring the packages"
-dotnet restore ${SRC_DIR}
 
+dotnet restore $PROJECT_DIR
 # configure some npm command during building
 export PATH="${PROJECT_DIR}/node_modules/.bin:${PATH}"
 
